controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
mon_panier_add:
    path: /mon-panier/add/{id}
    controller: App\Controller\MonPanierController::add
    
2fa_login_check:
    path: /2fa_check